# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_V4_proto1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(655, 670)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_sensors = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_sensors.sizePolicy().hasHeightForWidth())
        self.tab_sensors.setSizePolicy(sizePolicy)
        self.tab_sensors.setObjectName("tab_sensors")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_sensors)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridlayout_sensor = QtWidgets.QGridLayout()
        self.gridlayout_sensor.setObjectName("gridlayout_sensor")
        self.groupbox_sensor = QtWidgets.QGroupBox(self.tab_sensors)
        self.groupbox_sensor.setObjectName("groupbox_sensor")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupbox_sensor)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupbox_sensor1 = QtWidgets.QGroupBox(self.groupbox_sensor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupbox_sensor1.sizePolicy().hasHeightForWidth())
        self.groupbox_sensor1.setSizePolicy(sizePolicy)
        self.groupbox_sensor1.setObjectName("groupbox_sensor1")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupbox_sensor1)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verlayout_sensor1 = QtWidgets.QVBoxLayout()
        self.verlayout_sensor1.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verlayout_sensor1.setObjectName("verlayout_sensor1")
        self.horlayout_sensor1_1 = QtWidgets.QHBoxLayout()
        self.horlayout_sensor1_1.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horlayout_sensor1_1.setObjectName("horlayout_sensor1_1")
        self.combobox_sensor1_1 = QtWidgets.QComboBox(self.groupbox_sensor1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_sensor1_1.sizePolicy().hasHeightForWidth())
        self.combobox_sensor1_1.setSizePolicy(sizePolicy)
        self.combobox_sensor1_1.setObjectName("combobox_sensor1_1")
        self.horlayout_sensor1_1.addWidget(self.combobox_sensor1_1)
        self.lbl_sensor1_14 = QtWidgets.QLabel(self.groupbox_sensor1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_sensor1_14.sizePolicy().hasHeightForWidth())
        self.lbl_sensor1_14.setSizePolicy(sizePolicy)
        self.lbl_sensor1_14.setObjectName("lbl_sensor1_14")
        self.horlayout_sensor1_1.addWidget(self.lbl_sensor1_14)
        self.horlayout_sensor1_1.setStretch(0, 2)
        self.horlayout_sensor1_1.setStretch(1, 8)
        self.verlayout_sensor1.addLayout(self.horlayout_sensor1_1)
        self.horlayout_sensor1_2 = QtWidgets.QHBoxLayout()
        self.horlayout_sensor1_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horlayout_sensor1_2.setObjectName("horlayout_sensor1_2")
        self.combobox_sensor1_2 = QtWidgets.QComboBox(self.groupbox_sensor1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_sensor1_2.sizePolicy().hasHeightForWidth())
        self.combobox_sensor1_2.setSizePolicy(sizePolicy)
        self.combobox_sensor1_2.setObjectName("combobox_sensor1_2")
        self.horlayout_sensor1_2.addWidget(self.combobox_sensor1_2)
        self.lbl_sensor1_15 = QtWidgets.QLabel(self.groupbox_sensor1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_sensor1_15.sizePolicy().hasHeightForWidth())
        self.lbl_sensor1_15.setSizePolicy(sizePolicy)
        self.lbl_sensor1_15.setObjectName("lbl_sensor1_15")
        self.horlayout_sensor1_2.addWidget(self.lbl_sensor1_15)
        self.horlayout_sensor1_2.setStretch(0, 2)
        self.horlayout_sensor1_2.setStretch(1, 8)
        self.verlayout_sensor1.addLayout(self.horlayout_sensor1_2)
        self.horlayout_sensor1_3 = QtWidgets.QHBoxLayout()
        self.horlayout_sensor1_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horlayout_sensor1_3.setObjectName("horlayout_sensor1_3")
        self.combobox_sensor1_3 = QtWidgets.QComboBox(self.groupbox_sensor1)
        self.combobox_sensor1_3.setObjectName("combobox_sensor1_3")
        self.horlayout_sensor1_3.addWidget(self.combobox_sensor1_3)
        self.lbl_sensor1_16 = QtWidgets.QLabel(self.groupbox_sensor1)
        self.lbl_sensor1_16.setObjectName("lbl_sensor1_16")
        self.horlayout_sensor1_3.addWidget(self.lbl_sensor1_16)
        self.horlayout_sensor1_3.setStretch(0, 2)
        self.horlayout_sensor1_3.setStretch(1, 8)
        self.verlayout_sensor1.addLayout(self.horlayout_sensor1_3)
        self.gridLayout_7.addLayout(self.verlayout_sensor1, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupbox_sensor1, 0, 0, 1, 1)
        self.groupbox_sensor1_3 = QtWidgets.QGroupBox(self.groupbox_sensor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupbox_sensor1_3.sizePolicy().hasHeightForWidth())
        self.groupbox_sensor1_3.setSizePolicy(sizePolicy)
        self.groupbox_sensor1_3.setObjectName("groupbox_sensor1_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupbox_sensor1_3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.verlayout_sensor1_3 = QtWidgets.QVBoxLayout()
        self.verlayout_sensor1_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verlayout_sensor1_3.setObjectName("verlayout_sensor1_3")
        self.horlayout_sensor1_7 = QtWidgets.QHBoxLayout()
        self.horlayout_sensor1_7.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horlayout_sensor1_7.setObjectName("horlayout_sensor1_7")
        self.combobox_sensor1_7 = QtWidgets.QComboBox(self.groupbox_sensor1_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_sensor1_7.sizePolicy().hasHeightForWidth())
        self.combobox_sensor1_7.setSizePolicy(sizePolicy)
        self.combobox_sensor1_7.setObjectName("combobox_sensor1_7")
        self.horlayout_sensor1_7.addWidget(self.combobox_sensor1_7)
        self.lbl_sensor1_29 = QtWidgets.QLabel(self.groupbox_sensor1_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_sensor1_29.sizePolicy().hasHeightForWidth())
        self.lbl_sensor1_29.setSizePolicy(sizePolicy)
        self.lbl_sensor1_29.setObjectName("lbl_sensor1_29")
        self.horlayout_sensor1_7.addWidget(self.lbl_sensor1_29)
        self.horlayout_sensor1_7.setStretch(0, 2)
        self.horlayout_sensor1_7.setStretch(1, 8)
        self.verlayout_sensor1_3.addLayout(self.horlayout_sensor1_7)
        self.horlayout_sensor1_8 = QtWidgets.QHBoxLayout()
        self.horlayout_sensor1_8.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horlayout_sensor1_8.setObjectName("horlayout_sensor1_8")
        self.combobox_sensor1_8 = QtWidgets.QComboBox(self.groupbox_sensor1_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_sensor1_8.sizePolicy().hasHeightForWidth())
        self.combobox_sensor1_8.setSizePolicy(sizePolicy)
        self.combobox_sensor1_8.setObjectName("combobox_sensor1_8")
        self.horlayout_sensor1_8.addWidget(self.combobox_sensor1_8)
        self.lbl_sensor1_30 = QtWidgets.QLabel(self.groupbox_sensor1_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_sensor1_30.sizePolicy().hasHeightForWidth())
        self.lbl_sensor1_30.setSizePolicy(sizePolicy)
        self.lbl_sensor1_30.setObjectName("lbl_sensor1_30")
        self.horlayout_sensor1_8.addWidget(self.lbl_sensor1_30)
        self.horlayout_sensor1_8.setStretch(0, 2)
        self.horlayout_sensor1_8.setStretch(1, 8)
        self.verlayout_sensor1_3.addLayout(self.horlayout_sensor1_8)
        self.horlayout_sensor1_9 = QtWidgets.QHBoxLayout()
        self.horlayout_sensor1_9.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horlayout_sensor1_9.setObjectName("horlayout_sensor1_9")
        self.combobox_sensor1_9 = QtWidgets.QComboBox(self.groupbox_sensor1_3)
        self.combobox_sensor1_9.setObjectName("combobox_sensor1_9")
        self.horlayout_sensor1_9.addWidget(self.combobox_sensor1_9)
        self.lbl_sensor1_31 = QtWidgets.QLabel(self.groupbox_sensor1_3)
        self.lbl_sensor1_31.setObjectName("lbl_sensor1_31")
        self.horlayout_sensor1_9.addWidget(self.lbl_sensor1_31)
        self.horlayout_sensor1_9.setStretch(0, 2)
        self.horlayout_sensor1_9.setStretch(1, 8)
        self.verlayout_sensor1_3.addLayout(self.horlayout_sensor1_9)
        self.gridLayout_9.addLayout(self.verlayout_sensor1_3, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupbox_sensor1_3, 0, 2, 1, 1)
        self.groupbox_sensor1_4 = QtWidgets.QGroupBox(self.groupbox_sensor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupbox_sensor1_4.sizePolicy().hasHeightForWidth())
        self.groupbox_sensor1_4.setSizePolicy(sizePolicy)
        self.groupbox_sensor1_4.setObjectName("groupbox_sensor1_4")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupbox_sensor1_4)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verlayout_sensor1_5 = QtWidgets.QVBoxLayout()
        self.verlayout_sensor1_5.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verlayout_sensor1_5.setObjectName("verlayout_sensor1_5")
        self.horlayout_sensor1_10 = QtWidgets.QHBoxLayout()
        self.horlayout_sensor1_10.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horlayout_sensor1_10.setObjectName("horlayout_sensor1_10")
        self.combobox_sensor1_10 = QtWidgets.QComboBox(self.groupbox_sensor1_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_sensor1_10.sizePolicy().hasHeightForWidth())
        self.combobox_sensor1_10.setSizePolicy(sizePolicy)
        self.combobox_sensor1_10.setObjectName("combobox_sensor1_10")
        self.horlayout_sensor1_10.addWidget(self.combobox_sensor1_10)
        self.lbl_sensor1_35 = QtWidgets.QLabel(self.groupbox_sensor1_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_sensor1_35.sizePolicy().hasHeightForWidth())
        self.lbl_sensor1_35.setSizePolicy(sizePolicy)
        self.lbl_sensor1_35.setObjectName("lbl_sensor1_35")
        self.horlayout_sensor1_10.addWidget(self.lbl_sensor1_35)
        self.horlayout_sensor1_10.setStretch(0, 2)
        self.horlayout_sensor1_10.setStretch(1, 8)
        self.verlayout_sensor1_5.addLayout(self.horlayout_sensor1_10)
        self.horlayout_sensor1_11 = QtWidgets.QHBoxLayout()
        self.horlayout_sensor1_11.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horlayout_sensor1_11.setObjectName("horlayout_sensor1_11")
        self.combobox_sensor1_14 = QtWidgets.QComboBox(self.groupbox_sensor1_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_sensor1_14.sizePolicy().hasHeightForWidth())
        self.combobox_sensor1_14.setSizePolicy(sizePolicy)
        self.combobox_sensor1_14.setObjectName("combobox_sensor1_14")
        self.horlayout_sensor1_11.addWidget(self.combobox_sensor1_14)
        self.lbl_sensor1_36 = QtWidgets.QLabel(self.groupbox_sensor1_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_sensor1_36.sizePolicy().hasHeightForWidth())
        self.lbl_sensor1_36.setSizePolicy(sizePolicy)
        self.lbl_sensor1_36.setObjectName("lbl_sensor1_36")
        self.horlayout_sensor1_11.addWidget(self.lbl_sensor1_36)
        self.horlayout_sensor1_11.setStretch(0, 2)
        self.horlayout_sensor1_11.setStretch(1, 8)
        self.verlayout_sensor1_5.addLayout(self.horlayout_sensor1_11)
        self.horlayout_sensor1_12 = QtWidgets.QHBoxLayout()
        self.horlayout_sensor1_12.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horlayout_sensor1_12.setObjectName("horlayout_sensor1_12")
        self.combobox_sensor1_15 = QtWidgets.QComboBox(self.groupbox_sensor1_4)
        self.combobox_sensor1_15.setObjectName("combobox_sensor1_15")
        self.horlayout_sensor1_12.addWidget(self.combobox_sensor1_15)
        self.lbl_sensor1_37 = QtWidgets.QLabel(self.groupbox_sensor1_4)
        self.lbl_sensor1_37.setObjectName("lbl_sensor1_37")
        self.horlayout_sensor1_12.addWidget(self.lbl_sensor1_37)
        self.horlayout_sensor1_12.setStretch(0, 2)
        self.horlayout_sensor1_12.setStretch(1, 8)
        self.verlayout_sensor1_5.addLayout(self.horlayout_sensor1_12)
        self.gridLayout_10.addLayout(self.verlayout_sensor1_5, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupbox_sensor1_4, 1, 0, 1, 1)
        self.groupbox_sensor1_2 = QtWidgets.QGroupBox(self.groupbox_sensor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupbox_sensor1_2.sizePolicy().hasHeightForWidth())
        self.groupbox_sensor1_2.setSizePolicy(sizePolicy)
        self.groupbox_sensor1_2.setObjectName("groupbox_sensor1_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupbox_sensor1_2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verlayout_sensor1_2 = QtWidgets.QVBoxLayout()
        self.verlayout_sensor1_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verlayout_sensor1_2.setObjectName("verlayout_sensor1_2")
        self.horlayout_sensor1_4 = QtWidgets.QHBoxLayout()
        self.horlayout_sensor1_4.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horlayout_sensor1_4.setObjectName("horlayout_sensor1_4")
        self.combobox_sensor1_4 = QtWidgets.QComboBox(self.groupbox_sensor1_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_sensor1_4.sizePolicy().hasHeightForWidth())
        self.combobox_sensor1_4.setSizePolicy(sizePolicy)
        self.combobox_sensor1_4.setObjectName("combobox_sensor1_4")
        self.horlayout_sensor1_4.addWidget(self.combobox_sensor1_4)
        self.lbl_sensor1_20 = QtWidgets.QLabel(self.groupbox_sensor1_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_sensor1_20.sizePolicy().hasHeightForWidth())
        self.lbl_sensor1_20.setSizePolicy(sizePolicy)
        self.lbl_sensor1_20.setObjectName("lbl_sensor1_20")
        self.horlayout_sensor1_4.addWidget(self.lbl_sensor1_20)
        self.horlayout_sensor1_4.setStretch(0, 2)
        self.horlayout_sensor1_4.setStretch(1, 8)
        self.verlayout_sensor1_2.addLayout(self.horlayout_sensor1_4)
        self.horlayout_sensor1_5 = QtWidgets.QHBoxLayout()
        self.horlayout_sensor1_5.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horlayout_sensor1_5.setObjectName("horlayout_sensor1_5")
        self.combobox_sensor1_5 = QtWidgets.QComboBox(self.groupbox_sensor1_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_sensor1_5.sizePolicy().hasHeightForWidth())
        self.combobox_sensor1_5.setSizePolicy(sizePolicy)
        self.combobox_sensor1_5.setObjectName("combobox_sensor1_5")
        self.horlayout_sensor1_5.addWidget(self.combobox_sensor1_5)
        self.lbl_sensor1_21 = QtWidgets.QLabel(self.groupbox_sensor1_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_sensor1_21.sizePolicy().hasHeightForWidth())
        self.lbl_sensor1_21.setSizePolicy(sizePolicy)
        self.lbl_sensor1_21.setObjectName("lbl_sensor1_21")
        self.horlayout_sensor1_5.addWidget(self.lbl_sensor1_21)
        self.horlayout_sensor1_5.setStretch(0, 2)
        self.horlayout_sensor1_5.setStretch(1, 8)
        self.verlayout_sensor1_2.addLayout(self.horlayout_sensor1_5)
        self.horlayout_sensor1_6 = QtWidgets.QHBoxLayout()
        self.horlayout_sensor1_6.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horlayout_sensor1_6.setObjectName("horlayout_sensor1_6")
        self.combobox_sensor1_6 = QtWidgets.QComboBox(self.groupbox_sensor1_2)
        self.combobox_sensor1_6.setObjectName("combobox_sensor1_6")
        self.horlayout_sensor1_6.addWidget(self.combobox_sensor1_6)
        self.lbl_sensor1_22 = QtWidgets.QLabel(self.groupbox_sensor1_2)
        self.lbl_sensor1_22.setObjectName("lbl_sensor1_22")
        self.horlayout_sensor1_6.addWidget(self.lbl_sensor1_22)
        self.horlayout_sensor1_6.setStretch(0, 2)
        self.horlayout_sensor1_6.setStretch(1, 8)
        self.verlayout_sensor1_2.addLayout(self.horlayout_sensor1_6)
        self.gridLayout_8.addLayout(self.verlayout_sensor1_2, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupbox_sensor1_2, 0, 1, 1, 1)
        self.groupbox_sensor1_6 = QtWidgets.QGroupBox(self.groupbox_sensor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupbox_sensor1_6.sizePolicy().hasHeightForWidth())
        self.groupbox_sensor1_6.setSizePolicy(sizePolicy)
        self.groupbox_sensor1_6.setObjectName("groupbox_sensor1_6")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupbox_sensor1_6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.verlayout_sensor1_8 = QtWidgets.QVBoxLayout()
        self.verlayout_sensor1_8.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verlayout_sensor1_8.setObjectName("verlayout_sensor1_8")
        self.horlayout_sensor1_20 = QtWidgets.QHBoxLayout()
        self.horlayout_sensor1_20.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horlayout_sensor1_20.setObjectName("horlayout_sensor1_20")
        self.combobox_sensor1_22 = QtWidgets.QComboBox(self.groupbox_sensor1_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_sensor1_22.sizePolicy().hasHeightForWidth())
        self.combobox_sensor1_22.setSizePolicy(sizePolicy)
        self.combobox_sensor1_22.setObjectName("combobox_sensor1_22")
        self.horlayout_sensor1_20.addWidget(self.combobox_sensor1_22)
        self.lbl_sensor1_41 = QtWidgets.QLabel(self.groupbox_sensor1_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_sensor1_41.sizePolicy().hasHeightForWidth())
        self.lbl_sensor1_41.setSizePolicy(sizePolicy)
        self.lbl_sensor1_41.setObjectName("lbl_sensor1_41")
        self.horlayout_sensor1_20.addWidget(self.lbl_sensor1_41)
        self.horlayout_sensor1_20.setStretch(0, 2)
        self.horlayout_sensor1_20.setStretch(1, 8)
        self.verlayout_sensor1_8.addLayout(self.horlayout_sensor1_20)
        self.horlayout_sensor1_25 = QtWidgets.QHBoxLayout()
        self.horlayout_sensor1_25.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horlayout_sensor1_25.setObjectName("horlayout_sensor1_25")
        self.combobox_sensor1_23 = QtWidgets.QComboBox(self.groupbox_sensor1_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_sensor1_23.sizePolicy().hasHeightForWidth())
        self.combobox_sensor1_23.setSizePolicy(sizePolicy)
        self.combobox_sensor1_23.setObjectName("combobox_sensor1_23")
        self.horlayout_sensor1_25.addWidget(self.combobox_sensor1_23)
        self.lbl_sensor1_42 = QtWidgets.QLabel(self.groupbox_sensor1_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_sensor1_42.sizePolicy().hasHeightForWidth())
        self.lbl_sensor1_42.setSizePolicy(sizePolicy)
        self.lbl_sensor1_42.setObjectName("lbl_sensor1_42")
        self.horlayout_sensor1_25.addWidget(self.lbl_sensor1_42)
        self.horlayout_sensor1_25.setStretch(0, 2)
        self.horlayout_sensor1_25.setStretch(1, 8)
        self.verlayout_sensor1_8.addLayout(self.horlayout_sensor1_25)
        self.horlayout_sensor1_26 = QtWidgets.QHBoxLayout()
        self.horlayout_sensor1_26.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horlayout_sensor1_26.setObjectName("horlayout_sensor1_26")
        self.combobox_sensor1_24 = QtWidgets.QComboBox(self.groupbox_sensor1_6)
        self.combobox_sensor1_24.setObjectName("combobox_sensor1_24")
        self.horlayout_sensor1_26.addWidget(self.combobox_sensor1_24)
        self.lbl_sensor1_43 = QtWidgets.QLabel(self.groupbox_sensor1_6)
        self.lbl_sensor1_43.setObjectName("lbl_sensor1_43")
        self.horlayout_sensor1_26.addWidget(self.lbl_sensor1_43)
        self.horlayout_sensor1_26.setStretch(0, 2)
        self.horlayout_sensor1_26.setStretch(1, 8)
        self.verlayout_sensor1_8.addLayout(self.horlayout_sensor1_26)
        self.gridLayout_12.addLayout(self.verlayout_sensor1_8, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupbox_sensor1_6, 1, 2, 1, 1)
        self.groupbox_sensor1_5 = QtWidgets.QGroupBox(self.groupbox_sensor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupbox_sensor1_5.sizePolicy().hasHeightForWidth())
        self.groupbox_sensor1_5.setSizePolicy(sizePolicy)
        self.groupbox_sensor1_5.setObjectName("groupbox_sensor1_5")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupbox_sensor1_5)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.verlayout_sensor1_7 = QtWidgets.QVBoxLayout()
        self.verlayout_sensor1_7.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verlayout_sensor1_7.setObjectName("verlayout_sensor1_7")
        self.horlayout_sensor1_17 = QtWidgets.QHBoxLayout()
        self.horlayout_sensor1_17.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horlayout_sensor1_17.setObjectName("horlayout_sensor1_17")
        self.combobox_sensor1_16 = QtWidgets.QComboBox(self.groupbox_sensor1_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_sensor1_16.sizePolicy().hasHeightForWidth())
        self.combobox_sensor1_16.setSizePolicy(sizePolicy)
        self.combobox_sensor1_16.setObjectName("combobox_sensor1_16")
        self.horlayout_sensor1_17.addWidget(self.combobox_sensor1_16)
        self.lbl_sensor1_38 = QtWidgets.QLabel(self.groupbox_sensor1_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_sensor1_38.sizePolicy().hasHeightForWidth())
        self.lbl_sensor1_38.setSizePolicy(sizePolicy)
        self.lbl_sensor1_38.setObjectName("lbl_sensor1_38")
        self.horlayout_sensor1_17.addWidget(self.lbl_sensor1_38)
        self.horlayout_sensor1_17.setStretch(0, 2)
        self.horlayout_sensor1_17.setStretch(1, 8)
        self.verlayout_sensor1_7.addLayout(self.horlayout_sensor1_17)
        self.horlayout_sensor1_18 = QtWidgets.QHBoxLayout()
        self.horlayout_sensor1_18.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horlayout_sensor1_18.setObjectName("horlayout_sensor1_18")
        self.combobox_sensor1_20 = QtWidgets.QComboBox(self.groupbox_sensor1_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_sensor1_20.sizePolicy().hasHeightForWidth())
        self.combobox_sensor1_20.setSizePolicy(sizePolicy)
        self.combobox_sensor1_20.setObjectName("combobox_sensor1_20")
        self.horlayout_sensor1_18.addWidget(self.combobox_sensor1_20)
        self.lbl_sensor1_39 = QtWidgets.QLabel(self.groupbox_sensor1_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_sensor1_39.sizePolicy().hasHeightForWidth())
        self.lbl_sensor1_39.setSizePolicy(sizePolicy)
        self.lbl_sensor1_39.setObjectName("lbl_sensor1_39")
        self.horlayout_sensor1_18.addWidget(self.lbl_sensor1_39)
        self.horlayout_sensor1_18.setStretch(0, 2)
        self.horlayout_sensor1_18.setStretch(1, 8)
        self.verlayout_sensor1_7.addLayout(self.horlayout_sensor1_18)
        self.horlayout_sensor1_19 = QtWidgets.QHBoxLayout()
        self.horlayout_sensor1_19.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horlayout_sensor1_19.setObjectName("horlayout_sensor1_19")
        self.combobox_sensor1_21 = QtWidgets.QComboBox(self.groupbox_sensor1_5)
        self.combobox_sensor1_21.setObjectName("combobox_sensor1_21")
        self.horlayout_sensor1_19.addWidget(self.combobox_sensor1_21)
        self.lbl_sensor1_40 = QtWidgets.QLabel(self.groupbox_sensor1_5)
        self.lbl_sensor1_40.setObjectName("lbl_sensor1_40")
        self.horlayout_sensor1_19.addWidget(self.lbl_sensor1_40)
        self.horlayout_sensor1_19.setStretch(0, 2)
        self.horlayout_sensor1_19.setStretch(1, 8)
        self.verlayout_sensor1_7.addLayout(self.horlayout_sensor1_19)
        self.gridLayout_11.addLayout(self.verlayout_sensor1_7, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupbox_sensor1_5, 1, 1, 1, 1)
        self.groupbox_sensor1_7 = QtWidgets.QGroupBox(self.groupbox_sensor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupbox_sensor1_7.sizePolicy().hasHeightForWidth())
        self.groupbox_sensor1_7.setSizePolicy(sizePolicy)
        self.groupbox_sensor1_7.setObjectName("groupbox_sensor1_7")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupbox_sensor1_7)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.verlayout_sensor1_9 = QtWidgets.QVBoxLayout()
        self.verlayout_sensor1_9.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verlayout_sensor1_9.setObjectName("verlayout_sensor1_9")
        self.horlayout_sensor1_27 = QtWidgets.QHBoxLayout()
        self.horlayout_sensor1_27.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horlayout_sensor1_27.setObjectName("horlayout_sensor1_27")
        self.combobox_sensor1_25 = QtWidgets.QComboBox(self.groupbox_sensor1_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_sensor1_25.sizePolicy().hasHeightForWidth())
        self.combobox_sensor1_25.setSizePolicy(sizePolicy)
        self.combobox_sensor1_25.setObjectName("combobox_sensor1_25")
        self.horlayout_sensor1_27.addWidget(self.combobox_sensor1_25)
        self.lbl_sensor1_44 = QtWidgets.QLabel(self.groupbox_sensor1_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_sensor1_44.sizePolicy().hasHeightForWidth())
        self.lbl_sensor1_44.setSizePolicy(sizePolicy)
        self.lbl_sensor1_44.setObjectName("lbl_sensor1_44")
        self.horlayout_sensor1_27.addWidget(self.lbl_sensor1_44)
        self.horlayout_sensor1_27.setStretch(0, 2)
        self.horlayout_sensor1_27.setStretch(1, 8)
        self.verlayout_sensor1_9.addLayout(self.horlayout_sensor1_27)
        self.horlayout_sensor1_28 = QtWidgets.QHBoxLayout()
        self.horlayout_sensor1_28.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horlayout_sensor1_28.setObjectName("horlayout_sensor1_28")
        self.combobox_sensor1_26 = QtWidgets.QComboBox(self.groupbox_sensor1_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_sensor1_26.sizePolicy().hasHeightForWidth())
        self.combobox_sensor1_26.setSizePolicy(sizePolicy)
        self.combobox_sensor1_26.setObjectName("combobox_sensor1_26")
        self.horlayout_sensor1_28.addWidget(self.combobox_sensor1_26)
        self.lbl_sensor1_45 = QtWidgets.QLabel(self.groupbox_sensor1_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_sensor1_45.sizePolicy().hasHeightForWidth())
        self.lbl_sensor1_45.setSizePolicy(sizePolicy)
        self.lbl_sensor1_45.setObjectName("lbl_sensor1_45")
        self.horlayout_sensor1_28.addWidget(self.lbl_sensor1_45)
        self.horlayout_sensor1_28.setStretch(0, 2)
        self.horlayout_sensor1_28.setStretch(1, 8)
        self.verlayout_sensor1_9.addLayout(self.horlayout_sensor1_28)
        self.horlayout_sensor1_29 = QtWidgets.QHBoxLayout()
        self.horlayout_sensor1_29.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horlayout_sensor1_29.setObjectName("horlayout_sensor1_29")
        self.combobox_sensor1_27 = QtWidgets.QComboBox(self.groupbox_sensor1_7)
        self.combobox_sensor1_27.setObjectName("combobox_sensor1_27")
        self.horlayout_sensor1_29.addWidget(self.combobox_sensor1_27)
        self.lbl_sensor1_46 = QtWidgets.QLabel(self.groupbox_sensor1_7)
        self.lbl_sensor1_46.setObjectName("lbl_sensor1_46")
        self.horlayout_sensor1_29.addWidget(self.lbl_sensor1_46)
        self.horlayout_sensor1_29.setStretch(0, 2)
        self.horlayout_sensor1_29.setStretch(1, 8)
        self.verlayout_sensor1_9.addLayout(self.horlayout_sensor1_29)
        self.gridLayout_13.addLayout(self.verlayout_sensor1_9, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupbox_sensor1_7, 2, 0, 1, 1)
        self.groupbox_sensor1_8 = QtWidgets.QGroupBox(self.groupbox_sensor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupbox_sensor1_8.sizePolicy().hasHeightForWidth())
        self.groupbox_sensor1_8.setSizePolicy(sizePolicy)
        self.groupbox_sensor1_8.setObjectName("groupbox_sensor1_8")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupbox_sensor1_8)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.verlayout_sensor1_10 = QtWidgets.QVBoxLayout()
        self.verlayout_sensor1_10.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verlayout_sensor1_10.setObjectName("verlayout_sensor1_10")
        self.horlayout_sensor1_30 = QtWidgets.QHBoxLayout()
        self.horlayout_sensor1_30.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horlayout_sensor1_30.setObjectName("horlayout_sensor1_30")
        self.combobox_sensor1_28 = QtWidgets.QComboBox(self.groupbox_sensor1_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_sensor1_28.sizePolicy().hasHeightForWidth())
        self.combobox_sensor1_28.setSizePolicy(sizePolicy)
        self.combobox_sensor1_28.setObjectName("combobox_sensor1_28")
        self.horlayout_sensor1_30.addWidget(self.combobox_sensor1_28)
        self.lbl_sensor1_47 = QtWidgets.QLabel(self.groupbox_sensor1_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_sensor1_47.sizePolicy().hasHeightForWidth())
        self.lbl_sensor1_47.setSizePolicy(sizePolicy)
        self.lbl_sensor1_47.setObjectName("lbl_sensor1_47")
        self.horlayout_sensor1_30.addWidget(self.lbl_sensor1_47)
        self.horlayout_sensor1_30.setStretch(0, 2)
        self.horlayout_sensor1_30.setStretch(1, 8)
        self.verlayout_sensor1_10.addLayout(self.horlayout_sensor1_30)
        self.horlayout_sensor1_31 = QtWidgets.QHBoxLayout()
        self.horlayout_sensor1_31.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horlayout_sensor1_31.setObjectName("horlayout_sensor1_31")
        self.combobox_sensor1_29 = QtWidgets.QComboBox(self.groupbox_sensor1_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_sensor1_29.sizePolicy().hasHeightForWidth())
        self.combobox_sensor1_29.setSizePolicy(sizePolicy)
        self.combobox_sensor1_29.setObjectName("combobox_sensor1_29")
        self.horlayout_sensor1_31.addWidget(self.combobox_sensor1_29)
        self.lbl_sensor1_48 = QtWidgets.QLabel(self.groupbox_sensor1_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_sensor1_48.sizePolicy().hasHeightForWidth())
        self.lbl_sensor1_48.setSizePolicy(sizePolicy)
        self.lbl_sensor1_48.setObjectName("lbl_sensor1_48")
        self.horlayout_sensor1_31.addWidget(self.lbl_sensor1_48)
        self.horlayout_sensor1_31.setStretch(0, 2)
        self.horlayout_sensor1_31.setStretch(1, 8)
        self.verlayout_sensor1_10.addLayout(self.horlayout_sensor1_31)
        self.horlayout_sensor1_32 = QtWidgets.QHBoxLayout()
        self.horlayout_sensor1_32.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horlayout_sensor1_32.setObjectName("horlayout_sensor1_32")
        self.combobox_sensor1_30 = QtWidgets.QComboBox(self.groupbox_sensor1_8)
        self.combobox_sensor1_30.setObjectName("combobox_sensor1_30")
        self.horlayout_sensor1_32.addWidget(self.combobox_sensor1_30)
        self.lbl_sensor1_49 = QtWidgets.QLabel(self.groupbox_sensor1_8)
        self.lbl_sensor1_49.setObjectName("lbl_sensor1_49")
        self.horlayout_sensor1_32.addWidget(self.lbl_sensor1_49)
        self.horlayout_sensor1_32.setStretch(0, 2)
        self.horlayout_sensor1_32.setStretch(1, 8)
        self.verlayout_sensor1_10.addLayout(self.horlayout_sensor1_32)
        self.gridLayout_14.addLayout(self.verlayout_sensor1_10, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupbox_sensor1_8, 2, 1, 1, 1)
        self.groupbox_sensor1_9 = QtWidgets.QGroupBox(self.groupbox_sensor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupbox_sensor1_9.sizePolicy().hasHeightForWidth())
        self.groupbox_sensor1_9.setSizePolicy(sizePolicy)
        self.groupbox_sensor1_9.setObjectName("groupbox_sensor1_9")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupbox_sensor1_9)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.verlayout_sensor1_11 = QtWidgets.QVBoxLayout()
        self.verlayout_sensor1_11.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verlayout_sensor1_11.setObjectName("verlayout_sensor1_11")
        self.horlayout_sensor1_33 = QtWidgets.QHBoxLayout()
        self.horlayout_sensor1_33.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horlayout_sensor1_33.setObjectName("horlayout_sensor1_33")
        self.combobox_sensor1_31 = QtWidgets.QComboBox(self.groupbox_sensor1_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_sensor1_31.sizePolicy().hasHeightForWidth())
        self.combobox_sensor1_31.setSizePolicy(sizePolicy)
        self.combobox_sensor1_31.setObjectName("combobox_sensor1_31")
        self.horlayout_sensor1_33.addWidget(self.combobox_sensor1_31)
        self.lbl_sensor1_50 = QtWidgets.QLabel(self.groupbox_sensor1_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_sensor1_50.sizePolicy().hasHeightForWidth())
        self.lbl_sensor1_50.setSizePolicy(sizePolicy)
        self.lbl_sensor1_50.setObjectName("lbl_sensor1_50")
        self.horlayout_sensor1_33.addWidget(self.lbl_sensor1_50)
        self.horlayout_sensor1_33.setStretch(0, 2)
        self.horlayout_sensor1_33.setStretch(1, 8)
        self.verlayout_sensor1_11.addLayout(self.horlayout_sensor1_33)
        self.horlayout_sensor1_34 = QtWidgets.QHBoxLayout()
        self.horlayout_sensor1_34.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horlayout_sensor1_34.setObjectName("horlayout_sensor1_34")
        self.combobox_sensor1_32 = QtWidgets.QComboBox(self.groupbox_sensor1_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_sensor1_32.sizePolicy().hasHeightForWidth())
        self.combobox_sensor1_32.setSizePolicy(sizePolicy)
        self.combobox_sensor1_32.setObjectName("combobox_sensor1_32")
        self.horlayout_sensor1_34.addWidget(self.combobox_sensor1_32)
        self.lbl_sensor1_51 = QtWidgets.QLabel(self.groupbox_sensor1_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_sensor1_51.sizePolicy().hasHeightForWidth())
        self.lbl_sensor1_51.setSizePolicy(sizePolicy)
        self.lbl_sensor1_51.setObjectName("lbl_sensor1_51")
        self.horlayout_sensor1_34.addWidget(self.lbl_sensor1_51)
        self.horlayout_sensor1_34.setStretch(0, 2)
        self.horlayout_sensor1_34.setStretch(1, 8)
        self.verlayout_sensor1_11.addLayout(self.horlayout_sensor1_34)
        self.horlayout_sensor1_35 = QtWidgets.QHBoxLayout()
        self.horlayout_sensor1_35.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horlayout_sensor1_35.setObjectName("horlayout_sensor1_35")
        self.combobox_sensor1_33 = QtWidgets.QComboBox(self.groupbox_sensor1_9)
        self.combobox_sensor1_33.setObjectName("combobox_sensor1_33")
        self.horlayout_sensor1_35.addWidget(self.combobox_sensor1_33)
        self.lbl_sensor1_52 = QtWidgets.QLabel(self.groupbox_sensor1_9)
        self.lbl_sensor1_52.setObjectName("lbl_sensor1_52")
        self.horlayout_sensor1_35.addWidget(self.lbl_sensor1_52)
        self.horlayout_sensor1_35.setStretch(0, 2)
        self.horlayout_sensor1_35.setStretch(1, 8)
        self.verlayout_sensor1_11.addLayout(self.horlayout_sensor1_35)
        self.gridLayout_15.addLayout(self.verlayout_sensor1_11, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupbox_sensor1_9, 2, 2, 1, 1)
        self.gridlayout_sensor.addWidget(self.groupbox_sensor, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridlayout_sensor)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_sensor1 = AnalogGaugeWidget(self.tab_sensors)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_sensor1.sizePolicy().hasHeightForWidth())
        self.widget_sensor1.setSizePolicy(sizePolicy)
        self.widget_sensor1.setObjectName("widget_sensor1")
        self.horizontalLayout.addWidget(self.widget_sensor1)
        self.widget_sensor2 = AnalogGaugeWidget(self.tab_sensors)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_sensor2.sizePolicy().hasHeightForWidth())
        self.widget_sensor2.setSizePolicy(sizePolicy)
        self.widget_sensor2.setObjectName("widget_sensor2")
        self.horizontalLayout.addWidget(self.widget_sensor2)
        self.widget_sensor2_2 = AnalogGaugeWidget(self.tab_sensors)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_sensor2_2.sizePolicy().hasHeightForWidth())
        self.widget_sensor2_2.setSizePolicy(sizePolicy)
        self.widget_sensor2_2.setObjectName("widget_sensor2_2")
        self.horizontalLayout.addWidget(self.widget_sensor2_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 6)
        self.verticalLayout.setStretch(1, 4)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_sensors, "")
        self.tab_update = QtWidgets.QWidget()
        self.tab_update.setObjectName("tab_update")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_update)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Outter_Layout = QtWidgets.QVBoxLayout()
        self.Outter_Layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.Outter_Layout.setObjectName("Outter_Layout")
        self.lbl_binfile = QtWidgets.QLabel(self.tab_update)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_binfile.sizePolicy().hasHeightForWidth())
        self.lbl_binfile.setSizePolicy(sizePolicy)
        self.lbl_binfile.setObjectName("lbl_binfile")
        self.Outter_Layout.addWidget(self.lbl_binfile)
        self.lineEdit = QtWidgets.QLineEdit(self.tab_update)
        self.lineEdit.setObjectName("lineEdit")
        self.Outter_Layout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.tab_update)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.Outter_Layout.addWidget(self.pushButton)
        self.lbl_portnumber = QtWidgets.QLabel(self.tab_update)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_portnumber.sizePolicy().hasHeightForWidth())
        self.lbl_portnumber.setSizePolicy(sizePolicy)
        self.lbl_portnumber.setObjectName("lbl_portnumber")
        self.Outter_Layout.addWidget(self.lbl_portnumber)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_update)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.Outter_Layout.addWidget(self.lineEdit_2)
        self.lbl_checksum = QtWidgets.QLabel(self.tab_update)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_checksum.sizePolicy().hasHeightForWidth())
        self.lbl_checksum.setSizePolicy(sizePolicy)
        self.lbl_checksum.setObjectName("lbl_checksum")
        self.Outter_Layout.addWidget(self.lbl_checksum)
        self.checkBox = QtWidgets.QCheckBox(self.tab_update)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setObjectName("checkBox")
        self.Outter_Layout.addWidget(self.checkBox)
        self.label = QtWidgets.QLabel(self.tab_update)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.Outter_Layout.addWidget(self.label)
        self.text_label = QtWidgets.QLabel(self.tab_update)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_label.sizePolicy().hasHeightForWidth())
        self.text_label.setSizePolicy(sizePolicy)
        self.text_label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.text_label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.text_label.setLineWidth(0)
        self.text_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.text_label.setObjectName("text_label")
        self.Outter_Layout.addWidget(self.text_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.progressBar = QtWidgets.QProgressBar(self.tab_update)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_2.addWidget(self.progressBar)
        self.btn_done = QtWidgets.QPushButton(self.tab_update)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_done.sizePolicy().hasHeightForWidth())
        self.btn_done.setSizePolicy(sizePolicy)
        self.btn_done.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_done.setDefault(False)
        self.btn_done.setFlat(False)
        self.btn_done.setObjectName("btn_done")
        self.horizontalLayout_2.addWidget(self.btn_done)
        self.Outter_Layout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.tab_update)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_3.addWidget(self.buttonBox)
        self.Outter_Layout.addLayout(self.horizontalLayout_3)
        self.gridLayout_2.addLayout(self.Outter_Layout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_update, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 655, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupbox_sensor.setTitle(_translate("MainWindow", "GroupBox"))
        self.groupbox_sensor1.setTitle(_translate("MainWindow", "GroupBox"))
        self.lbl_sensor1_14.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_sensor1_15.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_sensor1_16.setText(_translate("MainWindow", "TextLabel"))
        self.groupbox_sensor1_3.setTitle(_translate("MainWindow", "GroupBox"))
        self.lbl_sensor1_29.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_sensor1_30.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_sensor1_31.setText(_translate("MainWindow", "TextLabel"))
        self.groupbox_sensor1_4.setTitle(_translate("MainWindow", "GroupBox"))
        self.lbl_sensor1_35.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_sensor1_36.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_sensor1_37.setText(_translate("MainWindow", "TextLabel"))
        self.groupbox_sensor1_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.lbl_sensor1_20.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_sensor1_21.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_sensor1_22.setText(_translate("MainWindow", "TextLabel"))
        self.groupbox_sensor1_6.setTitle(_translate("MainWindow", "GroupBox"))
        self.lbl_sensor1_41.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_sensor1_42.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_sensor1_43.setText(_translate("MainWindow", "TextLabel"))
        self.groupbox_sensor1_5.setTitle(_translate("MainWindow", "GroupBox"))
        self.lbl_sensor1_38.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_sensor1_39.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_sensor1_40.setText(_translate("MainWindow", "TextLabel"))
        self.groupbox_sensor1_7.setTitle(_translate("MainWindow", "GroupBox"))
        self.lbl_sensor1_44.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_sensor1_45.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_sensor1_46.setText(_translate("MainWindow", "TextLabel"))
        self.groupbox_sensor1_8.setTitle(_translate("MainWindow", "GroupBox"))
        self.lbl_sensor1_47.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_sensor1_48.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_sensor1_49.setText(_translate("MainWindow", "TextLabel"))
        self.groupbox_sensor1_9.setTitle(_translate("MainWindow", "GroupBox"))
        self.lbl_sensor1_50.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_sensor1_51.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_sensor1_52.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_sensors), _translate("MainWindow", "Sensors"))
        self.lbl_binfile.setText(_translate("MainWindow", "BIN File"))
        self.pushButton.setText(_translate("MainWindow", "File Select"))
        self.lbl_portnumber.setText(_translate("MainWindow", "Port Number"))
        self.lbl_checksum.setText(_translate("MainWindow", "Checksum Skip"))
        self.checkBox.setText(_translate("MainWindow", "ON"))
        self.label.setText(_translate("MainWindow", "Progress"))
        self.text_label.setText(_translate("MainWindow", "Log"))
        self.btn_done.setText(_translate("MainWindow", "Done"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_update), _translate("MainWindow", "Firmware"))

from analoggaugewidget import AnalogGaugeWidget
